**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
# A null vector is a vector in which every value is np.nan.
ans = np.full((10, ), np.nan)
ans

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [3]:
# Now change the element at position 5 i.e. at the index 4
ans[4] = 1

In [4]:
ans

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [5]:
a, b = map(int, input('Enter two numbers:').split(' '))

Enter two numbers:2 3


In [6]:
a, b

(2, 3)

In [7]:
ans = np.random.random((a, b))
ans

array([[0.34031932, 0.54575574, 0.21822851],
       [0.39282051, 0.48193109, 0.26079213]])

### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [8]:
def border_array(a, b):
    ans = np.zeros((a,b))
    
    # make 1st row as 1
    ans[0, ::] = 1
    
    # make last row as 1
    ans[-1, ::] = 1
    
    # make 1st col as 1
    ans[::, 0] = 1
    
    # make last col as 1
    ans[::, -1] = 1
    
    return ans

In [10]:
ans = np.random.random((4, 5))
ans

array([[0.18497655, 0.93298934, 0.57339269, 0.52369842, 0.0947031 ],
       [0.48099666, 0.1059902 , 0.9678407 , 0.65545486, 0.84951371],
       [0.57191445, 0.86055921, 0.44145062, 0.06435684, 0.82438372],
       [0.93621364, 0.60411141, 0.29837636, 0.57276652, 0.17396493]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [11]:
v = np.linspace(1, 10, 12)
v

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

#### `Now just remove the first and last element from this array so that we have total of 10 elements and all in (1, 10)`

In [12]:
ans = v[1:-1:]
ans

array([1.81818182, 2.63636364, 3.45454545, 4.27272727, 5.09090909,
       5.90909091, 6.72727273, 7.54545455, 8.36363636, 9.18181818])

In [13]:
ans.size

10

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [14]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [15]:
np.random.random((5,5)) * 4

array([[0.46424385, 1.53804432, 0.36220109, 1.45833306, 3.7908255 ],
       [2.56027696, 0.53385679, 2.90567431, 2.55188536, 3.07814548],
       [2.27537465, 3.9604397 , 2.38220358, 1.98559137, 0.7212735 ],
       [2.01118608, 1.8910198 , 3.85885016, 0.45779378, 2.10774377],
       [3.492349  , 2.68655627, 0.59028666, 1.54830229, 3.27214873]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [16]:
random_matrix = np.random.randint(1, 100, (10, 2))
point = np.array([2,3])

In [17]:
random_matrix

array([[61, 30],
       [42, 76],
       [46, 97],
       [48, 87],
       [50,  4],
       [44, 62],
       [30, 79],
       [24, 91],
       [81, 30],
       [93, 31]])

#### `we need to calculate the distance of each point in our random matrix from the point [2,3]`

In [19]:
distances = []

for rand_point in random_matrix:
    dist = (np.sum((rand_point - point) ** 2)) ** 0.5
    distances.append(dist)

distances

[64.88451279003334,
 83.24061508662703,
 103.78824596263297,
 95.77055915050303,
 48.010415536631214,
 72.42237223399962,
 80.99382692526635,
 90.70832376358854,
 83.48652585896721,
 95.2102935611481]

#### Approach 2

In [23]:
m = (random_matrix - point) ** 2
m

array([[3481,  729],
       [1600, 5329],
       [1936, 8836],
       [2116, 7056],
       [2304,    1],
       [1764, 3481],
       [ 784, 5776],
       [ 484, 7744],
       [6241,  729],
       [8281,  784]])

In [24]:
np.sum(m, axis = 1) # find the sum along the columns

array([ 4210,  6929, 10772,  9172,  2305,  5245,  6560,  8228,  6970,
        9065])

#### `Now we just need to take root of each individual values in the above array`

In [26]:
(np.sum(m, axis = 1)) ** 0.5

array([ 64.88451279,  83.24061509, 103.78824596,  95.77055915,
        48.01041554,  72.42237223,  80.99382693,  90.70832376,
        83.48652586,  95.21029356])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [28]:
nums = np.array(list(map(int, input("Enter the numbers: ").split(" "))))
nums = nums[::-1]
nums

Enter the numbers: 2 3 5 6 7


array([7, 6, 5, 3, 2])

In [29]:
# Approach 2 (better approach)
np.array(input("Enter the numbers: ").strip().split(" ")).astype(float)[::-1]

Enter the numbers: 2 3 4 5 7


array([7., 5., 4., 3., 2.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [30]:
#Code here
def ele_count(arr) -> int:
    return arr.size

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=1}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [31]:
def softmax(l):
    exponents = np.exp(l)
    sum_ = np.sum(exponents)
    
    return exponents/sum_

softmax([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [32]:
def my_vstack(*args) :
    try:
        return np.vstack(tuple(map(lambda l: np.array(l), args)))
    except ValueError as ex:
        return ValueError("Sorry cannot stack 'em")

my_vstack([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[1, 1, 1, 1, 1,], [1, 1, 1, 1, 1]], [3,4])

ValueError("Sorry cannot stack 'em")

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

### `Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [33]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
a[::, [0, 2, 1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### `Q-16:` Replace odd elements in arrays with -1.

In [35]:
def replace_odd(a):
    a[a%2 == 1] = -1
    return a

In [36]:
a = np.array([-3, 23, 45, 66, 89, 12, -90])
replace_odd(a)

array([ -1,  -1,  -1,  66,  -1,  12, -90])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [37]:
#Code here
def max_array(a, b):
    return np.max(np.vstack((a, b)),axis = 0)

In [38]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

max_array(a, b)

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [39]:
arr1=np.random.randint(low=1, high=10000, size= (40, )).reshape(8,5)
arr1

array([[8892, 4721, 7097, 2410, 5620],
       [8813, 5282,  711,   66, 8450],
       [2075, 1794, 1348, 9073, 2191],
       [8918, 9500, 8619, 2310, 2665],
       [4988, 2730, 3206, 6241, 1167],
       [4256, 8474, 8983,  462, 1998],
       [1823, 2120, 9972, 6518, 6317],
       [7309, 6089, 3680, 2903, 9123]])

In [40]:
𝑋 = arr1[::, ::2]
𝑋

array([[8892, 7097, 5620],
       [8813,  711, 8450],
       [2075, 1348, 2191],
       [8918, 8619, 2665],
       [4988, 3206, 1167],
       [4256, 8983, 1998],
       [1823, 9972, 6317],
       [7309, 3680, 9123]])

In [42]:
𝑋𝑚𝑖𝑛 = 𝑋.min()
𝑋𝑚𝑖𝑛

711

In [43]:
𝑋𝑚𝑎𝑥 = 𝑋.max()
𝑋𝑚𝑎𝑥

9972

In [44]:
(𝑋 - 𝑋𝑚𝑖𝑛)/(𝑋𝑚𝑎𝑥 - 𝑋𝑚𝑖𝑛)

array([[0.88338192, 0.68955836, 0.53007235],
       [0.87485153, 0.        , 0.8356549 ],
       [0.14728431, 0.06878307, 0.15980996],
       [0.8861894 , 0.85390347, 0.21099233],
       [0.46182918, 0.26940935, 0.04923874],
       [0.38278804, 0.89320808, 0.13896987],
       [0.12007343, 1.        , 0.6053342 ],
       [0.71245006, 0.32059173, 0.90832523]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [46]:
def nthmax(arr, n):
    if n > arr.size:
        return "Sorry, n is larger"
    else:
        arr.sort()
        return arr[-n]

In [47]:
a = np.array([12,34,40,7,1,0])
nthmax(a, 3)

12

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [46]:
def pattern(a):
    ans = [[ele] * len(a) for ele in a] # [[1,1,1], [2,2,2], [3,3,3]]
    ans.extend([a for ele in a])
    
    return np.ravel(ans) # np.ravel() is used to flatten the array

In [48]:
pattern([1, 2, 3, 4, 5])

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5])

### Approach 2

In [48]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [50]:
np.repeat(a, a.size) # np.repeat() is used to repeat an element specified number of times

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [51]:
np.tile(a, a.size)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [55]:
np.concatenate([np.repeat(a, a.size), np.tile(a, a.size)])

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5])