**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
# A null vector is a vector in which every value is np.nan.
ans = np.full(10, np.nan)
ans[4] = 1
ans

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
#Code here
a, b = map(int, input('Enter two numbers:').split(' '))
ans = np.random.random((a, b))
ans

Enter two numbers:2 3


array([[0.46495648, 0.26077187, 0.50070894],
       [0.50790722, 0.1244284 , 0.66622446]])

### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [13]:
#Code here
def border_array(a, b):
    ans = np.zeros((a,b))
    
    # make 1st row as 1
    ans[0, ::] = 1
    
    # make last row as 1
    ans[-1, ::] = 1
    
    # make 1st col as 1
    ans[::, 0] = 1
    
    # make last col as 1
    ans[::, -1] = 1
    
    return ans

border_array(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [15]:
#Code here
ans = np.linspace(0, 1, 12) # Now trim the first and last values
ans = ans[1:-1] # trimmed
ans

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [11]:
#Code here
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [12]:
#Code here
np.random.random((5,5)) * 4

array([[2.81746824, 3.74086565, 1.62069113, 1.11523745, 3.54956549],
       [3.52956662, 0.31072718, 2.03229179, 1.88380296, 0.94553614],
       [0.89876476, 1.93371196, 2.00403809, 3.16970315, 0.93361059],
       [1.58997213, 0.65547129, 0.01376118, 1.85820447, 3.69914754],
       [3.24531992, 2.47983807, 3.03934448, 3.58619689, 1.8365101 ]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [21]:
#code here

random_matrix = np.random.randint(1, 100, (10, 2))
point = np.array([2,3])

dist_array = []

for my_point in random_matrix:
    dist_array.append(np.sqrt(np.sum((my_point - point) ** 2)))
    
print(random_matrix)
dist_array

[[3 3]
 [3 4]
 [1 4]
 [3 5]
 [5 1]
 [5 1]
 [1 2]
 [4 5]
 [2 1]
 [3 3]]


[1.0,
 1.4142135623730951,
 1.4142135623730951,
 2.23606797749979,
 3.605551275463989,
 3.605551275463989,
 1.4142135623730951,
 2.8284271247461903,
 2.0,
 1.0]

#### Approach 2

In [29]:
np.random.seed(0)
random_matrix = np.random.randint(1, 100, (10, 2))
point = np.array([2,3])

# print((random_matrix - point) ** 2)
ans = np.sqrt(np.sum((random_matrix - point) ** 2, axis = 1))
ans

array([ 62.24146528,  90.52071586,  66.37017402,  84.17244205,
        91.92388155, 110.2587865 ,  87.57282684,  84.95881355,
        93.10746479,  97.06183596])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [30]:
# code
np.unravel_index(100, (6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [15]:
#Code here
nums = np.array(list(map(int, input("Enter the numbers: ").split(" "))))
nums = nums[::-1]
nums

Enter the numbers: 2 3 4 5


array([5, 4, 3, 2])

In [31]:
# Approach 2 (better approach)
np.array(input("Enter the numbers").strip().split(" ")).astype(float)

Enter the numbers2 3 4 5


array([2., 3., 4., 5.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [16]:
#Code here
def ele_count(arr) -> int:
    return arr.size

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=1}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [33]:
#Code here
def softmax(l):
    exponents = np.exp(l)
    sum_ = np.sum(exponents)
    
    return exponents/sum_

softmax([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [72]:
#Coder here

def my_vstack(*args) :
    try:
        return np.vstack(tuple(map(lambda l: np.array(l), args)))
    except ValueError as ex:
        return ValueError("Sorry cannot stack 'em")

my_vstack([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[1, 1, 1, 1, 1,], [1, 1, 1, 1, 1]], [3,4])

ValueError("Sorry cannot stack 'em")

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

### `Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

### `Q-16:` Replace odd elements in arrays with -1.

In [70]:
#Code here
def replace_odd(a):
    a[a%2 == 1] = -1
    return a

In [71]:
a = np.array([-3, 23, 45, 66, 89, 12, -90])
replace_odd(a)

array([ -1,  -1,  -1,  66,  -1,  12, -90])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [49]:
#Code here
def max_array(a, b):
    return np.max(np.vstack((a, b)),axis = 0)

In [50]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

max_array(a, b)

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [59]:
#Code here
def nthmax(arr, n):
    if n > arr.size:
        return "Sorry, n is larger"
    else:
        arr.sort()
        return arr[-n]

In [69]:
a = np.array([12,34,40,7,1,0])
nthmax(a, 3)

12

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [46]:
#code here
def pattern(a):
    ans = [[ele] * len(a) for ele in a] # [[1,1,1], [2,2,2], [3,3,3]]
    ans.extend([a for ele in a])
    
    return np.ravel(ans)

In [48]:
pattern([1,2,3, 4, 5])

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5])

### Approach 2

In [54]:
def pattern(a):
    part_one = np.repeat(a, len(a))
    part_two = np.tile(a, len(a))
    
    return np.hstack([part_one, part_two])

pattern([1,2,3,4,5])
    

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5])