## What is numpy?
- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## Numpy Arrays Vs Python Sequences
1. NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

2. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

3. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

4. A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

So basically around `2008`, people used to do data science using R programming language and Matlab. This was due to the fact that Python was considered a slow programming language(it still is to this date).

- So a bunch of people came around with the concept of numpy which is a library written in C language(this is one of the reasons it is very fast.)
- and they put a wrapper around it in the form of python(as python is very easy to learn)
- Fir kya uske baad se people started using python programming language for machine learning and data science.

# Creation of numpy arrays
- For creating a numpy array, we need to pass in a python list in the numpy.array() method.
- We can pass in a list of any dimension

In [1]:
import numpy as np

In [2]:
l = [1, 2, 3]

np.array(l)

array([1, 2, 3])

In [3]:
mat = [
        [1,2],
        [3,4]
    ]

In [4]:
np.array(mat)

array([[1, 2],
       [3, 4]])

In [5]:
tensor = [
            # first 2D array             
            [
                [1,2], 
                [3,4]
            ], 
            # second 2D array 
            [
                [11, 12],
                [34, 56]
            ],
            # third 2D array
            [
                [-1, -5],
                [-56, -68]
            ]
        ]

In [7]:
array = np.array(tensor)
array

array([[[  1,   2],
        [  3,   4]],

       [[ 11,  12],
        [ 34,  56]],

       [[ -1,  -5],
        [-56, -68]]])

In [8]:
array.ndim

3

- We can also create numpy arrays using the arange function. This is similar to the range() function
- This expects us to pass in 3 parameters : start, stop and step(jump)

In [9]:
np.arange(1, 20, 3) # 1, 4, 7, 10, 13, 16, 19

array([ 1,  4,  7, 10, 13, 16, 19])

#### Note
- It is a very common practice in data science to first create an array using arange() function and then reshape it to our convenience.
- The reshape() method expects us to pass in a tuple into which we want to convert our array.

In [10]:
np.arange(1,26).reshape((5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
np.arange(1,13).reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [12]:
np.arange(1,13).reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])